// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  App.Models.Item = (function(_super) {
    __extends(Item, _super);

    function Item() {
      return Item.__super__.constructor.apply(this, arguments);
    }

    Item.prototype.defaults = {
      id: null,
      parent_id: null,
      title: ''
    };

    Item.prototype.getChildren = function(id) {
      var children, item, result, _i, _len;
      result = this.collection.where({
        parent_id: id
      });
      for (_i = 0, _len = result.length; _i < _len; _i++) {
        item = result[_i];
        children = this.getChildren(item.id);
        if (!children.length) {
          continue;
        }
        _.each(children, function(item) {
          return result.push(item);
        });
      }
      return result;
    };

    Item.prototype.removeItem = function() {
      _.each(this.getChildren(this.id), function(item) {
        return item.destroy();
      });
      return this.destroy();
    };

    return Item;

  })(Backbone.Model);

}).call(this);
