// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  App.Models.Item = (function(_super) {
    __extends(Item, _super);

    function Item() {
      return Item.__super__.constructor.apply(this, arguments);
    }

    Item.prototype.defaults = {
      id: null,
      parent_id: null,
      title: ''
    };

    Item.prototype.removeItem = function() {
      var item, _i, _len, _ref;
      _ref = this.collection.where({
        parent_id: this.id
      });
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        this.removeItem.apply(item);
      }
      return this.destroy();
    };

    return Item;

  })(Backbone.Model);

}).call(this);
